### ISSUE TITLE
No clear indication of failed 2fa token entry

### ISSUE THREAD

**Issue by budak7273** [SatisfactoryServerManager/SSMCloud#9]
(Copy pasted from https://github.com/mrhid6/SatisfactoryServerManager/issues/311)

Describe the bug
Poor feedback for the user when failing to correctly enter your 2fa token

To Reproduce

    Be signed out
    Go to sign in
    Enter your correct username and password
    Enter and submit an incorrect 2fa code
    The box is cleared and nothing else seems to happen

Expected behavior
A message/popup/banner appears saying "Incorrect 2fa code" or similar

image

Server Information (please complete the following information):

    OS: Irrelevant
    SSM Version: 1.0.121

Additional context
Also, it should not be possible to submit the Verify Token forum when a token of less than 6 digits is entered

**Comment by mrhid6** [comment]
Resolved - 1.0.122
